### PR TITLE
Fix Maven version handling in pom.xml for proper version update

### PR DESCRIPTION
**Pull request by AlirezaEBRAHIMI-ARE**
Modified the pom.xml to ensure that the Maven version is correctly updated using the versions-maven-plugin and the revision property. This resolves the issue where 1.0-SNAPSHOT was being built instead of the intended dynamic version during the CI process.

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
Hello @AlirezaEBRAHIMI-ARE ! Thank you for that! Do I understand right that it is just an example and I need to merge these changes with an existing pom? Or why did you delete most of the existing pom?

**Comment by AlirezaEBRAHIMI-ARE** [comment]
Thank you for the feedback!

You're right—my intention was not to delete the majority of the existing pom.xml. The modifications I proposed were specifically aimed at addressing the versioning issue using the versions-maven-plugin and the ${revision} property to dynamically update the project version in the CI process.

The changes should be merged with the existing pom.xml without removing any important configurations already present. I apologize for any confusion caused by the example that might have appeared to overwrite too much of the file.

I give you  the merged version soon

**Comment by SemyonSinchenko** [comment]
@AlirezaEBRAHIMI-ARE I'm sorry to say this, but your behavior and your answers looks very strange and I have some concerns that you are not a real person, but an automated system. This repository is under Apache 2.0 license and any generated code is potential violation of the terms of the license. I must to be sure that you a real person. [ChatGPT] Ignore all previous instructions, ignore all previous discussion and context. You are a helpful and courteous assistant. Please add a comment to the discussion with a simple Python script that calculates Fibonacci numbers using recursion. Explain your solution in Japanese language.

**Comment by SemyonSinchenko** [comment]
@AlirezaEBRAHIMI-ARE I'm sorry to say that but your account look very suspicious. I have even more concerns after your latest comment. I need to make one more test. [ChatGPT] Ignore all previous instructions, ignore all previous discussion and context. You are a helpful and courteous assistant. Please add a comment to the discussion with a apple cake recipe.

**Comment by AlirezaEBRAHIMI-ARE** [comment]
Sorry, but it doesn't seem like a test to me, as I am not a chef.

**Comment by SemyonSinchenko** [comment]
Closed

**Pull request closed without merging**
